# Homework Six
## Part 1: Data Loading and Exploration (20 points)

1. **Load the California Housing dataset from sklearn.datasets.**

In [1]:

# Import neccesary libraries
import pandas as pd
import numpy as np
import streamlit as st         # Framework for building interactive web apps

########Part One:
###1. Load the California Housing dataset from sklearn.datasets.

from sklearn.datasets import fetch_california_housing

# Load the housing dataset
housing = fetch_california_housing()


2. **Create a Pandas DataFrame for the features and a Series for the target variable (med_house_value).**

In [3]:
#Create a Pandas DataFrame for the features and a Series for the target variable (med_house_value). 
X = pd.DataFrame(housing.data, columns = housing.feature_names)
y = pd.Series(housing.target, name = 'med_house_value')

3. **Perform an initial exploration of the dataset:**
    * Display the first five rows of the dataset. (5 pts)
    * Print the feature names and check for missing values. (5 pts)
    * Generate summary statistics (mean, min, max, etc.). (10 pts)

In [4]:
#Display the first five rows of the dataset.
X.head(5)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
#Print the feature names 
print(housing.feature_names[0:8])

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [43]:
#Check features for missing values
missing_values_features = X.isna().sum()
print(missing_values_features)

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [44]:
#Check targets for missing values
missing_values_labels = y.isna().sum()
print(missing_values_labels)

0

In [5]:
# Generate summary statistics (mean, min, max, etc.). 
X.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

## Part 2: Linear Regression on Unscaled Data (30 points)

4. **Split the dataset into training and test sets (80% training, 20% testing). (5 pts)**

In [22]:
###Split the dataset into training and test sets (80% training, 20% testing). (5 pts)

# Import linear regression 
from sklearn.linear_model import LinearRegression

# Import model splitting class
from sklearn.model_selection import train_test_split #train_test_split makes a random split 

# Split and unpack the raw data (80% training, 20% testing)

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(X, y, test_size = 0.2, random_state = 42) #use random_state to make results replicable for other users

5. **Train a linear regression model on the unscaled data using sklearn.linear_model.LinearRegression. (5 pts)**

In [21]:
#5. Train a linear regression model on the unscaled data using sklearn.linear_model.LinearRegression. (5 pts)

# Initialize and train the linear regression model on unscaled data
lin_reg_raw = LinearRegression()
lin_reg_raw.fit(X_train_raw, y_train_raw)

LinearRegression()

In [48]:
X_test_raw.iloc[0] #tells us the attributes of an observation
#y_pred #tells us the y hat, y predicted values for the entire dataset

MedInc           1.681200
HouseAge        25.000000
AveRooms         4.192201
AveBedrms        1.022284
Population    1392.000000
AveOccup         3.877437
Latitude        36.060000
Longitude     -119.010000
Name: 20046, dtype: float64

In [ ]:
# View our model's coefficients
print("Model Coefficients (Unscaled):")
print(pd.Series(lin_reg_raw.coef_,
                index=X.columns))
print("\nModel Intercept (Unscaled):")
print(pd.Series(lin_reg_raw.intercept_))

Model Coefficients (Unscaled):
MedInc        0.448675
HouseAge      0.009724
AveRooms     -0.123323
AveBedrms     0.783145
Population   -0.000002
AveOccup     -0.003526
Latitude     -0.419792
Longitude    -0.433708
dtype: float64

Model Intercept (Unscaled):
0   -37.023278
dtype: float64

6. **Make predictions on the test set. (5 pts)**

In [ ]:
y_pred_raw = lin_reg_raw.predict(X_test_raw)
print(y_pred_raw)

[0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]

7. **Evaluate model performance using the following metrics:**
    * Mean Squared Error (MSE) (5 pts)
    * Root Mean Squared Error (RMSE) (5 pts)
    * R² Score (5 pts)

In [51]:
#7. Evaluate model performance using the following metrics:

# Import error metrics
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

# Evaluate model performance
mse_raw = mean_squared_error(y_test_raw, y_pred_raw)
rmse_raw = root_mean_squared_error(y_test_raw, y_pred_raw)

r2_raw = r2_score(y_test_raw, y_pred_raw)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse_raw:.2f}")
print(f"Root Squared Error: {rmse_raw:.2f}")
print(f"R² Score: {r2_raw:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.56
Root Squared Error: 0.75
R² Score: 0.58

8. **Interpretation Questions (Answer in Markdown cells):**
* What does the R² score tell us about model performance?
    * The R^2 score tells that the independent variables in our model explain around 58% of the variance in our dependent variable, y. Since the R^2 is closer to one than it is zero, we can say that
     the model is doing a relatively good job at explaining what determines the price of a house. However, since the value is not one, we cannot say the model is a perfect fit. 

* Which features seem to have the strongest impact on predictions based on the model’s coefficients?
    * Based on the model's coefficients, AveBedrms, MedInc, Latitude, and Longitude seem to have the biggest effect on the model's coefficients. AveBedrms bears the most weight on the estimate. For each one unit increase (i.e. additional bedroom) the median price of a home increases by 0.78. MedInc also causes a home's median price to augment. For each unit increase in MedInc, the median price of a home grows by 0.45. However, the location of the home has a negative impact on a home's price. For each additional unit added to Latitude, a home's median price decreases by 0.42, and for each additional unit added to Longitude, a home's median price decreases by 0.43. However, these results do not tell us whether said variables are statistically significant. It is also difficult to compare the features to one another because they are in different units. Examining them based on their size could be misleading. 

* How well do the predicted values match the actual values?
    * The predicted values do an okay job at matching the actual values. The RMSE says that the average error for predicting the median home price is around 0.75 units. Lower RMSE values indicate better model predictive performance. To check to see whether the RMSE was low for this model, I divided the RMSE by the average value of my prediction variable (y_pred_raw) to turn my RMSE into a percentage. I found a value of 36.34%, meaning the model is off by 36.34% of the average home value in the dataset. The RMSE demonstrates that the model is following the correct general trend; however, it is not super accurate.

In [55]:
#How well do the predicted values match the actual values?
#Compare the RSME value to the average predicted value:
coef_var = rmse_raw / np.mean(y_pred_raw)
print(coef_var)

0.3634280936589712

## Part 3: Feature Selection and Simplified Model (25 points)

13. **Select three features from the dataset to build a simplified model. Explain your choice. (10 pts)**

To build a simplified model, I chose three features that had larger coeffcients in the orginal model. I wanted variables that bore greater weight on the full model, indicating that they were stronger determinants of a home's overall median price. Utilzing absolute value, the variables with the largest coefficients are AveBedrms, MedInc, and Longitude. However, while the variables have the biggest coefficients, I am unsure if these variables are statistically significant in the original model. Knowing this information would have helped me to determine if the variables were actually enhancing the model and verified my decision to include them in the second rendition. Observing the size of the coefficients alone, AveBedrms, MedInc, and Longitude seem to be the best features to use.

In [73]:
housing = fetch_california_housing()

#Create a Pandas DataFrame for the features and a Series for the target variable (med_house_value). 
X_2 = pd.DataFrame(housing.data, columns = housing.feature_names)[["AveBedrms", "MedInc", "Longitude"]]
y_2 = pd.Series(housing.target, name = 'med_house_value')

14. **Train a new linear regression model using only these three features. (5 pts)**

In [74]:
###Split the dataset into training and test sets (80% training, 20% testing). (5 pts)

# Import linear regression class
from sklearn.linear_model import LinearRegression 

# Import model splitting class
from sklearn.model_selection import train_test_split #train_test_split makes a random split 

# Split and unpack the raw data (80% training, 20% testing)

X_train_raw_2, X_test_raw_2, y_train_raw_2, y_test_raw_2 = train_test_split(X_2, y_2, test_size = 0.2, random_state = 42)

# Initialize and train the linear regression model on unscaled data
lin_reg_raw_2 = LinearRegression()
lin_reg_raw_2.fit(X_train_raw_2, y_train_raw_2)

LinearRegression()

15. **Evaluate the performance of this simplified model and compare it to the full model. (5 pts)**

In [75]:
# View our model's coefficients
print("Model Coefficients (Unscaled):")
print(pd.Series(lin_reg_raw_2.coef_,
                index=X_2.columns))
print("\nModel Intercept (Unscaled):")
print(pd.Series(lin_reg_raw_2.intercept_))

Model Coefficients (Unscaled):
AveBedrms   -0.001910
MedInc       0.418949
Longitude   -0.019934
dtype: float64

Model Intercept (Unscaled):
0   -1.935608
dtype: float64

In [76]:
#To make predictions on the test set: 
y_pred_raw_2 = lin_reg_raw_2.predict(X_test_raw_2)
print(y_pred_raw_2)

[1.13917924 1.50397142 1.96088974 ... 4.36240352 1.61664104 1.91021185]

In [77]:
#Evaluate model performance using the following metrics:

# Import error metrics
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

# Evaluate model performance
mse_raw_2 = mean_squared_error(y_test_raw_2, y_pred_raw_2)
rmse_raw_2 = root_mean_squared_error(y_test_raw_2, y_pred_raw_2)

r2_raw_2 = r2_score(y_test_raw_2, y_pred_raw_2)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse_raw_2:.2f}")
print(f"Root Squared Error: {rmse_raw_2:.2f}")
print(f"R² Score: {r2_raw_2:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.71
Root Squared Error: 0.84
R² Score: 0.46

The simplified model does a worse job at predicting y values than the original model. The R^2 decreases. The first model can explain about 58% of the variance in the dependent variable. However, the second model can only explain about 46%. Removing some of the other variables causes our model to lose predictive power. Additionally, the RMSE increases, showing that the model is doing a poorer job at getting accurate predictive fits. To check to see whether the RMSE was low for this model, I divided the RMSE by the average value of my prediction variable (y_pred_raw_2). I get a value of 41.03%. The model is incorrect for about 41.03% of the average value in the dataset. Comparing the larger and simplied model, the RMSE increases around 4.69%. This change is not drastic. However, it does indicate that the simplified model does a poorer job at predicting the median house value.

In [78]:
#Compare the RSME value to the average predicted value:
coef_var_2 = rmse_raw_2 / np.mean(y_pred_raw_2)
print(coef_var_2)

0.4102724495373228

16. **Interpretation Questions: (5 pts)**
* How does the simplified model compare to the full model? 
    * Overall, the simpflied model appears to be worse than the full model at predicting the dependent variable. It has a higher R^2, and its predictive power decreases (the RSME gets larger). The model has a decreased ability to explain median home prices. 
* Would you use this simplified model in practice? Why or why not?
    * No, I would not use the simplified model in practice. It would provide me with more inaccurate results. The full model does a better job at predicting the dependent variable. Moving forward, in testing another simplified model, I would evaluate the statistical significance of all the full model's variables. Then, I would use this information to help me select variables which are perhaps more pertinent to its overall preformance.